### ISSUE TITLE
Labels de tipos de humedal / SAR

### ISSUE THREAD

**Issue by nmorandeira** [prosathumedales/extraccion_muestras#8]
Las etiquetas de **tipo_humed** deben quedar así (la sintaxis de este "diccionario" es de R):

`labels6 <- c("Albardones_y_derrames_con_bosques", "Espiras_con_bosques", "Espiras_con_mosaico_de_herbaceas", "Lagunas_asociadas_a_espiras", "Lagunas_de_bajos", "Media_lomas_y_bajos_con_mosaico_de_herbaceas")`

Actualmente hay diferencias de acuerdo a la unidad de paisaje y/o de acuerdo al sensor, lo que me da un total de 8 clases en lugar de 6. 
No es urgente.
No me doy cuenta si el error surge del script de Python o si venía del shp.

**Comment by nmorandeira** [comment]
por si sirve, este es el código que usé en R:

capa$tipo_humed  <-gsub("bosque","bosques",as.character(capa$tipo_humed))  
capa$tipo_humed  <-gsub("bosquess","bosques",as.character(capa$tipo_humed)) 
capa$tipo_humed  <-gsub("bajo","bajos",as.character(capa$tipo_humed)) 
capa$tipo_humed  <-gsub("bajoss","bajos",as.character(capa$tipo_humed))

**Comment by marielaraj** [comment]
Buenas, revise los shapefiles que tenia yo y en uno utilizaba "bosque" y en el otro "bosques", calculo que habrá pasado lo mismo con "bajo" y "bajos". Se puede emparchar como hiciste en R pero tal vez acá sería mejor modificarlo en los shapefiles.

**Comment by nmorandeira** [comment]
Gracias por revisar! Lo había revisado y no lo vi. Ahí encontré la diferencia entre shapefiles
